// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: flogram.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum FLAGS: SwiftProtobuf.Enum {
  public typealias RawValue = Int
  case v1 // = 0
  case tg // = 1
  case fromUser // = 2
  case fromGroup // = 3
  case fromChannel // = 4
  case fromChannelPublic // = 5
  case UNRECOGNIZED(Int)

  public init() {
    self = .v1
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .v1
    case 1: self = .tg
    case 2: self = .fromUser
    case 3: self = .fromGroup
    case 4: self = .fromChannel
    case 5: self = .fromChannelPublic
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .v1: return 0
    case .tg: return 1
    case .fromUser: return 2
    case .fromGroup: return 3
    case .fromChannel: return 4
    case .fromChannelPublic: return 5
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension FLAGS: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [FLAGS] = [
    .v1,
    .tg,
    .fromUser,
    .fromGroup,
    .fromChannel,
    .fromChannelPublic,
  ]
}

#endif  // swift(>=4.2)

public struct FLO_SOURCE {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var flags: Int32 = 0

  public var fromPeerID: Int64 = 0

  public var toPeerID: Int64 = 0

  public var topicUid: String = String()

  public var title: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct FLO_MESSAGE {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var flags: Int32 = 0

  public var fromPeerID: Int64 = 0

  public var toPeerID: Int64 = 0

  public var createdAt: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _createdAt ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_createdAt = newValue}
  }
  /// Returns true if `createdAt` has been explicitly set.
  public var hasCreatedAt: Bool {return self._createdAt != nil}
  /// Clears the value of `createdAt`. Subsequent reads from it will return its default value.
  public mutating func clearCreatedAt() {self._createdAt = nil}

  public var title: String = String()

  public var text: String = String()

  public var topicUid: String = String()

  public var messageLinks: [String] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _createdAt: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
}

public struct FlotgMonitor {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var flags: Int32 = 0

  public var fromPeerID: Int64 = 0

  public var topicUid: String = String()

  public var monitoringEnabled: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct FloRssHosting {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var flags: Int32 = 0

  public var topicUid: String = String()

  public var title: String = String()

  public var fromPeerID: String = String()

  public var rssUri: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct FloRssCreate {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var flags: Int32 = 0

  public var topicUid: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

#if swift(>=5.5) && canImport(_Concurrency)
extension FLAGS: @unchecked Sendable {}
extension FLO_SOURCE: @unchecked Sendable {}
extension FLO_MESSAGE: @unchecked Sendable {}
extension FlotgMonitor: @unchecked Sendable {}
extension FloRssHosting: @unchecked Sendable {}
extension FloRssCreate: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension FLAGS: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "V1"),
    1: .same(proto: "Tg"),
    2: .same(proto: "FromUser"),
    3: .same(proto: "FromGroup"),
    4: .same(proto: "FromChannel"),
    5: .same(proto: "FromChannelPublic"),
  ]
}

extension FLO_SOURCE: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "FLO_SOURCE"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "flags"),
    2: .standard(proto: "from_peer_id"),
    3: .standard(proto: "to_peer_id"),
    4: .standard(proto: "topic_uid"),
    5: .same(proto: "title"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.flags) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.fromPeerID) }()
      case 3: try { try decoder.decodeSingularInt64Field(value: &self.toPeerID) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.topicUid) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.title) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.flags != 0 {
      try visitor.visitSingularInt32Field(value: self.flags, fieldNumber: 1)
    }
    if self.fromPeerID != 0 {
      try visitor.visitSingularInt64Field(value: self.fromPeerID, fieldNumber: 2)
    }
    if self.toPeerID != 0 {
      try visitor.visitSingularInt64Field(value: self.toPeerID, fieldNumber: 3)
    }
    if !self.topicUid.isEmpty {
      try visitor.visitSingularStringField(value: self.topicUid, fieldNumber: 4)
    }
    if !self.title.isEmpty {
      try visitor.visitSingularStringField(value: self.title, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: FLO_SOURCE, rhs: FLO_SOURCE) -> Bool {
    if lhs.flags != rhs.flags {return false}
    if lhs.fromPeerID != rhs.fromPeerID {return false}
    if lhs.toPeerID != rhs.toPeerID {return false}
    if lhs.topicUid != rhs.topicUid {return false}
    if lhs.title != rhs.title {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension FLO_MESSAGE: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "FLO_MESSAGE"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "flags"),
    2: .standard(proto: "from_peer_id"),
    3: .standard(proto: "to_peer_id"),
    4: .standard(proto: "created_at"),
    5: .same(proto: "title"),
    6: .same(proto: "text"),
    7: .standard(proto: "topic_uid"),
    8: .standard(proto: "message_links"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.flags) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.fromPeerID) }()
      case 3: try { try decoder.decodeSingularInt64Field(value: &self.toPeerID) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._createdAt) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.title) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.text) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.topicUid) }()
      case 8: try { try decoder.decodeRepeatedStringField(value: &self.messageLinks) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.flags != 0 {
      try visitor.visitSingularInt32Field(value: self.flags, fieldNumber: 1)
    }
    if self.fromPeerID != 0 {
      try visitor.visitSingularInt64Field(value: self.fromPeerID, fieldNumber: 2)
    }
    if self.toPeerID != 0 {
      try visitor.visitSingularInt64Field(value: self.toPeerID, fieldNumber: 3)
    }
    try { if let v = self._createdAt {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    if !self.title.isEmpty {
      try visitor.visitSingularStringField(value: self.title, fieldNumber: 5)
    }
    if !self.text.isEmpty {
      try visitor.visitSingularStringField(value: self.text, fieldNumber: 6)
    }
    if !self.topicUid.isEmpty {
      try visitor.visitSingularStringField(value: self.topicUid, fieldNumber: 7)
    }
    if !self.messageLinks.isEmpty {
      try visitor.visitRepeatedStringField(value: self.messageLinks, fieldNumber: 8)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: FLO_MESSAGE, rhs: FLO_MESSAGE) -> Bool {
    if lhs.flags != rhs.flags {return false}
    if lhs.fromPeerID != rhs.fromPeerID {return false}
    if lhs.toPeerID != rhs.toPeerID {return false}
    if lhs._createdAt != rhs._createdAt {return false}
    if lhs.title != rhs.title {return false}
    if lhs.text != rhs.text {return false}
    if lhs.topicUid != rhs.topicUid {return false}
    if lhs.messageLinks != rhs.messageLinks {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension FlotgMonitor: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "FlotgMonitor"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "flags"),
    2: .standard(proto: "from_peer_id"),
    3: .standard(proto: "topic_uid"),
    4: .standard(proto: "monitoring_enabled"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.flags) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.fromPeerID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.topicUid) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self.monitoringEnabled) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.flags != 0 {
      try visitor.visitSingularInt32Field(value: self.flags, fieldNumber: 1)
    }
    if self.fromPeerID != 0 {
      try visitor.visitSingularInt64Field(value: self.fromPeerID, fieldNumber: 2)
    }
    if !self.topicUid.isEmpty {
      try visitor.visitSingularStringField(value: self.topicUid, fieldNumber: 3)
    }
    if self.monitoringEnabled != false {
      try visitor.visitSingularBoolField(value: self.monitoringEnabled, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: FlotgMonitor, rhs: FlotgMonitor) -> Bool {
    if lhs.flags != rhs.flags {return false}
    if lhs.fromPeerID != rhs.fromPeerID {return false}
    if lhs.topicUid != rhs.topicUid {return false}
    if lhs.monitoringEnabled != rhs.monitoringEnabled {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension FloRssHosting: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "FloRssHosting"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "flags"),
    2: .standard(proto: "topic_uid"),
    3: .same(proto: "title"),
    4: .standard(proto: "from_peer_id"),
    5: .standard(proto: "rss_uri"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.flags) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.topicUid) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.title) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.fromPeerID) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.rssUri) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.flags != 0 {
      try visitor.visitSingularInt32Field(value: self.flags, fieldNumber: 1)
    }
    if !self.topicUid.isEmpty {
      try visitor.visitSingularStringField(value: self.topicUid, fieldNumber: 2)
    }
    if !self.title.isEmpty {
      try visitor.visitSingularStringField(value: self.title, fieldNumber: 3)
    }
    if !self.fromPeerID.isEmpty {
      try visitor.visitSingularStringField(value: self.fromPeerID, fieldNumber: 4)
    }
    if !self.rssUri.isEmpty {
      try visitor.visitSingularStringField(value: self.rssUri, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: FloRssHosting, rhs: FloRssHosting) -> Bool {
    if lhs.flags != rhs.flags {return false}
    if lhs.topicUid != rhs.topicUid {return false}
    if lhs.title != rhs.title {return false}
    if lhs.fromPeerID != rhs.fromPeerID {return false}
    if lhs.rssUri != rhs.rssUri {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension FloRssCreate: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "FloRssCreate"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "flags"),
    2: .standard(proto: "topic_uid"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.flags) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.topicUid) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.flags != 0 {
      try visitor.visitSingularInt32Field(value: self.flags, fieldNumber: 1)
    }
    if !self.topicUid.isEmpty {
      try visitor.visitSingularStringField(value: self.topicUid, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: FloRssCreate, rhs: FloRssCreate) -> Bool {
    if lhs.flags != rhs.flags {return false}
    if lhs.topicUid != rhs.topicUid {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
