
# Extension to main docker-compose.yml

volumes:
  gopkg:
  gocache:

services:

  wayout-lib-devcontainer:
    network_mode: host
    build: 
      context: .
      dockerfile: devcontainer.swift.Dockerfile
    volumes:
      - ./wayout-lib:/root/wayout-lib
      # using remote paths:
      #- /remote/workspace/wayout-lib:/root/wayout-lib
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"

  flo_rss-devcontainer:
    network_mode: host
    build: 
      context: .
      dockerfile: devcontainer.swift.Dockerfile
    environment:
      WAYOUT_CLI_CONF_DIR: ~/.wayout-cli
    volumes:
      - ./flo_rss:/root/flo_rss
      - ./wayout-lib:/root/wayout-lib
      # using remote paths:
      #- ./flo_rss:/root/flo_rss
      #- ./wayout-lib:/root/wayout-lib
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"

  flo_tg-devcontainer:
    network_mode: host
    build: 
      context: .
      dockerfile: devcontainer.go.Dockerfile
    env_file: .env
    environment:
      FLOTG_PORT: "${FLOTG_PORT:?Please set FLOTG_PORT in the .env file}"
      GRAYLOG_ADDRESS: "${GRAYLOG_ADDRESS:?Please set GRAYLOG_ADDRESS in the .env file}"
      MONGO_URI: "${MONGO_URI:?Please set MONGO_URI in the .env file}"
      TG_PHONE: "${TG_PHONE:?Please set TG_PHONE in the .env file}"
      TG_APP_ID: "${TG_APP_ID:?Please set TG_APP_ID in the .env file}"
      TG_APP_HASH: "${TG_APP_HASH:?Please set TG_APP_HASH in the .env file}"
      TG_SESSION_PATH: /var/run/telegram-session
      GOCACHE: /go/cache
      GOPATH: /go
    volumes:
      - telegram-session:/var/run/telegram-session
      - gopkg:/go/pkg
      - gocache:/go/cache
      - ./flo_tg:/root/flo_tg
      # using remote paths:
      #- ./flo_tg:/root/flo_tg
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"