
# Extension to main docker-compose.yml

volumes:
  gopkg:
  gocache:

services:

  wayout-lib-devcontainer:
    build: 
      context: .
      dockerfile: devcontainer.swift.Dockerfile
    volumes:
      - ./wayout-lib:/root/wayout-lib
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"

  flo_rss-devcontainer:
    build: 
      context: .
      dockerfile: devcontainer.swift.Dockerfile
    environment:
      WAYOUT_CLI_CONF_DIR: ~/.wayout-cli
    volumes:
      - ./flo_rss:/root/flo_rss
      - ./wayout-lib:/root/wayout-lib
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"

  flo_tg-devcontainer:
    build: 
      context: .
      dockerfile: devcontainer.go.Dockerfile
    env_file: .env
    environment:
      FLOTG_PORT: "${FLOTG_PORT:?Please set FLOTG_PORT in the .env file}"
      GRAYLOG_ADDRESS: 10.8.0.1:12201
      MONGO_URI: mongodb://10.8.0.1:27017
      TG_PHONE: "${TG_PHONE:?Please set TG_PHONE in the .env file}"
      TG_APP_ID: "${TG_APP_ID:?Please set TG_APP_ID in the .env file}"
      TG_APP_HASH: "${TG_APP_HASH:?Please set TG_APP_HASH in the .env file}"
      TG_SESSION_PATH: /var/run/telegram-session
      GOCACHE: /go/cache
      GOPATH: /go
    volumes:
      - telegram-session:/var/run/telegram-session
      - ./flo_tg:/root/flo_tg
      - gopkg:/go/pkg
      - gocache:/go/cache
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"